// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gagoyrkvhixqldtlddyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZ295cmt2aGl4cWxkdGxkZHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDUwMjYsImV4cCI6MjA3NDIyMTAyNn0.ptmMI6C8RmZoTPBqHl-uzywkGhfk-fizUABdJs-K7Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});